overwrite: true
schema: ./src/graphql/schema.gql
documents: ./src/graphql/operation.gql
generates:
  ./src/graphql/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
