query Posts {
  posts {
    ...PostFragment
  }
}

query Post($id: String!) {
  post(id: $id) {
    ...PostFragment
  }
}

query User($username: String!) {
  user(name: $username) {
    ...UserFragment
  }
}

mutation RegisterUser($user: UserCreateInput!) {
  createUser(user: $user) {
    ...UserFragment
  }
}

fragment PostFragment on Post {
  id
  content
  createdAt
}

fragment UserFragment on User {
  id
  name
  email
  cover
  createdAt
  image
  displayName
}
